# Generated by Django 5.2.1 on 2025-05-15 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_eventmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodel',
            name='number',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
